#!/usr/bin/perl

# take in a pgn-formatted game and output a tsv describing each move:
# halfmove [tab] SAN [tab] from-to [tab] FEN

use strict;
use warnings;

use Chess::Rep;
use JSON qw(encode_json);

my $pgn = join('', <>);
$pgn =~ s/\s*$//;

my @moves = grep { $_ !~ /\./ } split /\s+/, $pgn;

my @fens;

my $halfturn = 1;
my $game = Chess::Rep->new();
for my $san (@moves) {
    my $done = $game->go_move($san);
    push @fens, $game->get_fen;
}

print "var clock_fens=" . encode_json(\@fens) . ";\n";
